// Generated by CoffeeScript 1.7.1

/*


 File: superphy-spec.coffee
 Desc: Jasmine test cases. Tests logic of the Superphy JS lib
 Author: Matt Whiteside matthew.whiteside@phac-aspc.gc.ca
 Date: March 21th, 2013
 */

(function() {


}).call(this);
