language: perl
perl:
  - "5.14"
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y r-base-core
  - sudo apt-get install -y r-base-dev
  - sudo apt-get install nodejs
  - sudo apt-get install nodejs-legacy 
script: "perl Build.PL && ./Build && travis_wait npm test && ./Build test"