// Generated by CoffeeScript 1.7.1

/*


 File: genes_info.coffee
 Desc: Javascript functions for the genes/info page
 Author: Matt Whiteside matthew.whiteside@phac-aspc.gc.ca
 Date: May 27th, 2013
 */

(function() {
  var alignmentRequest, categoryView, retrieveGeneAlignment, root, _categoryHtml;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  categoryView = function(categoryObj, el) {
    var genHtml, html, midHtml, topHtml, wrapEl;
    html = '<div class="gene-info-category-wrapper">';
    topHtml = _categoryHtml(categoryObj.top, true);
    html += "<div class='top-category'>" + topHtml + "</div>";
    midHtml = _categoryHtml(categoryObj.category);
    html += "<div class='middle-category'>" + midHtml + "</div>";
    genHtml = _categoryHtml(categoryObj.gene);
    html += "<div class='gene-category'>" + genHtml + "</div>";
    return wrapEl = jQuery(html).appendTo(el);
  };

  if (!root.categoryView) {
    root.categoryView = categoryView;
  }

  _categoryHtml = function(catObj, top) {
    var header, html;
    if (top == null) {
      top = false;
    }
    header = catObj.name[0].toUpperCase() + catObj.name.slice(1);
    html = "<h5><i class='fa fa-chevron-right'></i> " + header + "</h5>";
    if (catObj.definition) {
      html += "<p>" + catObj.definition + "</p>";
    }
    return html;
  };

  retrieveGeneAlignment = function(geneID, locusData) {
    var alignmentRequest, serializedParams;
    if (alignmentRequest) {
      alignmentRequest.abort();
    }
    serializedParams = {
      'gene': geneID
    };
    console.log('Sending gene alignment request');
    alignmentRequest = jQuery.ajax({
      url: "superphy/genes/sequences",
      type: "post",
      data: serializedParams
    });
    alignmentRequest.done(function(data, textStatus, jqXHR) {
      var parentDiv;
      console.log('Alignment retrieval success');
      parentDiv = jQuery('#gene-info-msa');
      parentDiv.empty();
      return viewController.createView('msa', parentDiv, data, locusData);
    });
    alignmentRequest.fail(function(jqXHR, textStatus, errorThrown) {
      console.error("Error! AJAX retrieval of gene alignment failed: " + textStatus + ",  " + errorThrown + ".");
      return jQuery('#msa_download_inprogress').html('<div class="alert alert-danger">' + '<p style="text-align:center">Retrieval of gene alignment encountered error.</p>');
    });
    return true;
  };

  if (!root.retrieveGeneAlignment) {
    root.retrieveGeneAlignment = retrieveGeneAlignment;
  }

  alignmentRequest = null;

  if (!root.alignmentRequest) {
    root.alignmentRequest = alignmentRequest;
  }

}).call(this);
