// Generated by CoffeeScript 1.8.0

/*


 File: intro_example.coffee
 Desc: Coffeescript example for introJS
 Author: Matt Whiteside matthew.whiteside@phac-aspc.gc.ca
 Date: Sept 5, 2014
 

 Name all files like this intro_[page_name].coffee

 Compiled coffeescript files will be sent to App/Lib/js/. This directory
 contains all Superphy's js files. So this naming scheme will help ensure 
 there are no filename collisions.

 Cakefile has a routine to compile and output the coffeescript files
 in intro/ to js/. To run:

   cake intro
 */

(function() {
  var root, startIntro;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  startIntro = function() {
    var intro;
    intro = introJs();
    intro.setOptions({
      steps: [
        {
          intro: "Hello world! "
        }, {
          element: document.querySelector('.title_part1'),
          intro: "This is a tooltip. ",
          position: 'right'
        }, {
          element: document.querySelector('#genome_selection_window'),
          intro: "Ok, wasn't that fun? "
        }
      ]
    });
    intro.start();
    return false;
  };

  if (!root.startIntro) {
    root.startIntro = startIntro;
  }

}).call(this);
