// Generated by CoffeeScript 1.8.0

/*


 File: intro_genes_lookup.coffee
 Desc: Coffeescript for genes/lookup page intros
 Author: Jason Masih jason.masih@phac-aspc.gc.ca
 Date: Sept 22, 2014
 

 Name all files like this intro_[page_name].coffee

 Compiled coffeescript files will be sent to App/Lib/js/. This directory
 contains all Superphy's js files. So this naming scheme will help ensure 
 there are no filename collisions.

 Cakefile has a routine to compile and output the coffeescript files
 in intro/ to js/. To run:

   cake intro
 */

(function() {
  var root, startIntro;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  startIntro = function() {
    var intro;
    intro = introJs();
    intro.setOptions({
      steps: [
        {
          element: document.querySelector('#vfgenes'),
          intro: "Use this to look up detailed information about individual virulence factors.  The search bar can be used to filter virulence factors in the list.",
          position: 'top'
        }, {
          element: document.querySelector('#amrgenes'),
          intro: "Use this to look up detailed information about individual antimicrobial resistance genes. The search bar can be used to filter antimicrobial resistance factors in the list.",
          position: 'top'
        }
      ]
    });
    intro.start();
    return false;
  };

  if (!root.startIntro) {
    root.startIntro = startIntro;
  }

}).call(this);
