// Generated by CoffeeScript 1.8.0

/*


 File: intro_groups_search.coffee
 Desc: CoffeeScript for groups/search page intros
 Author: Jason Masih jason.masih@phac-aspc.gc.ca
 Date: Sept 9, 2014
 

 Name all files like this intro_[page_name].coffee

 Compiled coffeescript files will be sent to App/Lib/js/. This directory
 contains all Superphy's js files. So this naming scheme will help ensure 
 there are no filename collisions.

 Cakefile has a routine to compile and output the coffeescript files
 in intro/ to js/. To run:

   cake intro
 */

(function() {
  var root, startIntro;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  startIntro = function() {
    var intro, opts;
    opts = viewController.introOptions();
    opts.splice(0, 0, {
      intro: "Welcome to SuperPhy's Group Analyses page."
    });
    opts.splice(2, 0, {
      element: document.querySelector('#genome-group-list1'),
      intro: "This is the Group 1 box.",
      position: 'bottom'
    }, {
      element: document.querySelector('#genome-group-list2'),
      intro: "This is the Group 2 box.",
      position: 'bottom'
    });
    intro = introJs();
    intro.setOptions({
      steps: opts
    });
    intro.start();
    return false;
  };

  if (!root.startIntro) {
    root.startIntro = startIntro;
  }

}).call(this);
