// Generated by CoffeeScript 1.7.1

/*


 File: pangenomes_info.coffee
 Desc: Javascript functions for the genes/info page
 Author: Matt Whiteside matthew.whiteside@phac-aspc.gc.ca
 Date: Aug 8th, 2015
 */

(function() {
  var alignmentRequest, retrievePgAlignment, root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  retrievePgAlignment = function(regionID, locusData) {
    var alignmentRequest, serializedParams;
    if (alignmentRequest) {
      alignmentRequest.abort();
    }
    serializedParams = {
      'region': regionID
    };
    console.log('Sending gene alignment request');
    alignmentRequest = jQuery.ajax({
      url: "/superphy/pangenomes/sequences",
      type: "post",
      data: serializedParams
    });
    alignmentRequest.done(function(data, textStatus, jqXHR) {
      var parentDiv;
      parentDiv = jQuery('#pangenome-info-msa');
      parentDiv.empty();
      return viewController.createView('msa', parentDiv, data, locusData);
    });
    alignmentRequest.fail(function(jqXHR, textStatus, errorThrown) {
      console.error("Error! AJAX retrieval of gene alignment failed: " + textStatus + ",  " + errorThrown + ".");
      return jQuery('#msa_download_inprogress').html('<div class="alert alert-danger">' + '<p style="text-align:center">Retrieval of gene alignment encountered error.</p>');
    });
    return true;
  };

  if (!root.retrievePgAlignment) {
    root.retrievePgAlignment = retrievePgAlignment;
  }

  alignmentRequest = null;

  if (!root.alignmentRequest) {
    root.alignmentRequest = alignmentRequest;
  }

}).call(this);
