// Generated by CoffeeScript 1.9.3

/*


File: superphy_user_groups.coffee
Desc: Objects & functions for managing user created groups in Superphy
Author: Akiff Manji akiff.manji@gmail.com
Date: Sept 8th, 2014
 */

(function() {
  var SuperphyError, UserGroups, root,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  root = typeof exports !== "undefined" && exports !== null ? exports : this;


  /*
  CLASS SuperphyError
  
  Error object for this library
   */

  SuperphyError = (function(superClass) {
    extend(SuperphyError, superClass);

    function SuperphyError(message, name1) {
      this.message = message != null ? message : '';
      this.name = name1 != null ? name1 : 'Superphy Error';
    }

    return SuperphyError;

  })(Error);

  UserGroups = (function() {
    var initialBonsaiState;

    function UserGroups(userGroupsObj, username, parentElem, viewController1, public_genomes1, private_genomes1) {
      this.userGroupsObj = userGroupsObj;
      this.username = username;
      this.parentElem = parentElem;
      this.viewController = viewController1;
      this.public_genomes = public_genomes1;
      this.private_genomes = private_genomes1;
      this._updateSelections = bind(this._updateSelections, this);
      this._removeCategoryRadio = bind(this._removeCategoryRadio, this);
      this._getGroupGenomes = bind(this._getGroupGenomes, this);
      this._processGroups = bind(this._processGroups, this);
      this.appendGroupForm = bind(this.appendGroupForm, this);
      if (!this.userGroupsObj) {
        throw new SuperphyError('User groups object cannot be empty/null.');
      }
      if (!this.parentElem) {
        throw new SuperphyError('Parent div not specified.');
      }
      if (!this.viewController) {
        throw new SuperphyError('ViewController object is required');
      }
      this.user_custom_collections = {};
      this.user_custom_groups = {};
      this.runSelect = false;
      this.groupSelected = false;
      this.active_group = {
        group_id: '',
        public_list: [],
        private_list: [],
        group_name: ''
      };
      this.appendGroupForm(this.userGroupsObj);
    }

    initialBonsaiState = {};

    UserGroups.prototype.appendGroupForm = function(uGpObj) {
      var container, createGroupPane, createGroupsTab, create_group_form, custom_select, group_create_button, group_delete_button, group_query_input, group_select, group_update, group_update_button, group_update_button_row, group_update_input, group_update_input_row, loadGroupPane, loadGroupsTab, load_group, load_group_row, load_groups_button, load_groups_button2, load_groups_form, myWorker, standard_select, tabPanes, tabUl;
      container = jQuery('<div id="user-groups-selectize-form"></div>').appendTo(this.parentElem);
      tabUl = jQuery('<ul class="nav nav-tabs"></ul>').appendTo(container);
      loadGroupsTab = jQuery('<li role="presentation" class="active"><a href="#load-groups" role="tab" data-toggle="tab">Load</a></li>').appendTo(tabUl);
      createGroupsTab = jQuery('<li role="presentation"><a href="#create-groups" role="tab" data-toggle="tab">Modify/Delete</a></li>').appendTo(tabUl);
      tabPanes = jQuery('<div class="tab-content"></div>').appendTo(container);
      loadGroupPane = jQuery('<div role="tabpanel" class="tab-pane active" id="load-groups"></div>').appendTo(tabPanes);
      load_groups_form = jQuery('<form class="form"></form>').appendTo(loadGroupPane);
      group_select = jQuery('<div class="control-group" style="margin-top:5px"></div>').appendTo(load_groups_form);
      if (window.Worker) {
        myWorker = new Worker("../App/Lib/js/worker/group_builder.js");
        myWorker.postMessage(JSON.stringify(uGpObj));
        myWorker.onmessage = (function(_this) {
          return function(e) {
            var bonsai, standard_select;
            standard_select = jQuery(e.data).prependTo(group_select);
            bonsai = $('.group-list').bonsai({
              createInputs: 'radio',
              checkboxes: true
            });
            bonsai = $('.group-list').data('bonsai');
            _this._removeCategoryRadio();
            initialBonsaiState = bonsai.serialize();
            return 1;
          };
        })(this);
      } else {
        standard_select = jQuery(this.bonsaiUserGroupList(uGpObj)).appendTo(group_select);
      }
      group_query_input = jQuery('<input id="group-query-input" type="hidden" data-group="" data-genome_list="">').appendTo(group_select);
      load_group = jQuery('<div class="form-group" style="margin-bottom:0px"></div>').appendTo(load_groups_form);
      load_group_row = jQuery('<div class="row"></div>').appendTo(load_group);
      load_groups_button = jQuery('button#user-groups-submit');
      load_groups_button2 = $('<div class="col-md-3"><button class="btn btn-sm" type="button">Load</button></div>').appendTo(load_group_row);
      load_groups_button.click((function(_this) {
        return function(e) {
          var data, group_number, select_ids;
          e.preventDefault();
          data = $('#group-query-input').data();
          group_number = $('input[name=undefined]:checked', '.group-list').val();
          data = $("li[id=bonsai" + group_number + "]", '.group-list');
          select_ids = _this._getGroupGenomes(group_number, _this.public_genomes, _this.private_genomes);
          _this._updateSelections(select_ids, group_number, data.genome_list);
          return _this.customSelectizeControl.clear();
        };
      })(this));
      load_groups_button2.click((function(_this) {
        return function(e) {
          var data, group_number, select_ids;
          e.preventDefault();
          data = $('#group-query-input').data();
          group_number = $('input[name=undefined]:checked', '.group-list').val();
          data = $("li[id=bonsai" + group_number + "]", '.group-list');
          select_ids = _this._getGroupGenomes(group_number, _this.public_genomes, _this.private_genomes);
          _this._updateSelections(select_ids, group_number, data.genome_list);
          return _this.customSelectizeControl.clear();
        };
      })(this));
      createGroupPane = jQuery('<div role="tabpanel" class="tab-pane" id="create-groups"></div>').appendTo(tabPanes);
      create_group_form = jQuery('<form class="form"></form>').appendTo(createGroupPane);
      group_update = jQuery('<div class="form-group"></div>').appendTo(create_group_form);
      if (this.username === "") {
        custom_select = jQuery('<p>Please <a href="/superphy/user/login">sign in</a> to view your custom groups</p>');
        group_update_input_row = jQuery('<div style="margin-top:5px"><p>Please <a href="/superphy/user/login">sign in</a> to create, update and delete groups</p></div>').appendTo(group_update);
      } else {
        custom_select = jQuery('<select id="custom_group_collections" class="form-control" placeholder="Select custom group(s)..."></select>');
        group_update_input_row = jQuery('<div class="row" style="margin-top:5px"></div>').appendTo(group_update);
        group_update_input = jQuery('<div class="col-xs-12">' + '<input class="form-control input-sm" type="text" id="create_group_name_input" placeholder="Group Name">' + '<input style="margin-top:5px" class="form-control input-sm" type="text" id="create_collection_name_input" placeholder="Collection Name">' + '<input style="margin-top:5px" class="form-control input-sm" type="text" id="create_description_input" placeholder="Description">' + '</div>').appendTo(group_update_input_row);
        group_update_button_row = jQuery('<div class="row" style="margin-top:5px"></div>').appendTo(group_update);
        group_create_button = jQuery('<div class="col-xs-3"><button class="btn btn-sm" type="button">Create</button></div>').appendTo(group_update_button_row);
        group_update_button = jQuery('<div class="col-xs-3"><button class="btn btn-sm" type="button">Update</button></div>').appendTo(group_update_button_row);
        group_delete_button = jQuery('<div class="col-xs-3"><button class="btn btn-sm" type="button">Delete</button></div>').appendTo(group_update_button_row);
        group_create_button.click((function(_this) {
          return function(e) {
            var data, data_str, g, g_obj, ref, ref1;
            e.preventDefault();
            data = [];
            ref = _this.viewController.genomeController.public_genomes;
            for (g in ref) {
              g_obj = ref[g];
              if (g_obj.isSelected) {
                data.push('genome=' + g);
              }
            }
            ref1 = _this.viewController.genomeController.private_genomes;
            for (g in ref1) {
              g_obj = ref1[g];
              if (g_obj.isSelected) {
                data.push('genome=' + g);
              }
            }
            data_str = data.join('&');
            return jQuery.ajax({
              type: "GET",
              url: '/superphy/collections/create?' + data_str,
              data: {
                'name': $('#create_group_name_input').val(),
                'category': $('#create_collection_name_input').val(),
                'description': $('#create_description_input').val()
              }
            }).done(function(data) {
              var ref2, ref3;
              console.log(data);
              if (data.success === 1) {
                ref2 = usrGrp.viewController.genomeController.public_genomes;
                for (g in ref2) {
                  g_obj = ref2[g];
                  if (g_obj.isSelected) {
                    if (!(g_obj.groups.indexOf(data.group_id) > -1)) {
                      g_obj.groups.push(data.group_id);
                    }
                  }
                }
                ref3 = usrGrp.viewController.genomeController.private_genomes;
                for (g in ref3) {
                  g_obj = ref3[g];
                  if (g_obj.isSelected) {
                    if (!(g_obj.groups.indexOf(data.group_id) > -1)) {
                      g_obj.groups.push(data.group_id);
                    }
                  }
                }
                $('#user-groups-selectize-form').remove();
                return _this.appendGroupForm(data.groups);
              }
            }).fail((function(error) {
              return console.log(error);
            }));
          };
        })(this));
        group_update_button.click((function(_this) {
          return function(e) {
            var data, data_str, g, g_obj, group_id, name, ref, ref1;
            data = [];
            ref = _this.viewController.genomeController.public_genomes;
            for (g in ref) {
              g_obj = ref[g];
              if (g_obj.isSelected) {
                data.push('genome=' + g);
              }
            }
            ref1 = _this.viewController.genomeController.private_genomes;
            for (g in ref1) {
              g_obj = ref1[g];
              if (g_obj.isSelected) {
                data.push('genome=' + g);
              }
            }
            data_str = data.join('&');
            name = $('#create_group_name_input').val();
            group_id = _this.user_custom_groups[name];
            console.log(name);
            console.log(group_id);
            e.preventDefault();
            return jQuery.ajax({
              type: "GET",
              url: '/superphy/collections/update?' + data_str,
              data: {
                'group_id': group_id,
                'name': name,
                'category': $('#create_collection_name_input').val(),
                'description': $('#create_description_input').val()
              }
            }).done(function(data) {
              var ref2, ref3;
              console.log(data);
              if (data.success === 1) {
                ref2 = usrGrp.viewController.genomeController.public_genomes;
                for (g in ref2) {
                  g_obj = ref2[g];
                  if (g_obj.isSelected) {
                    if (!(g_obj.groups.indexOf(data.group_id) > -1)) {
                      g_obj.groups.push(data.group_id);
                    }
                  }
                }
                ref3 = usrGrp.viewController.genomeController.private_genomes;
                for (g in ref3) {
                  g_obj = ref3[g];
                  if (g_obj.isSelected) {
                    if (!(g_obj.groups.indexOf(data.group_id) > -1)) {
                      g_obj.groups.push(data.group_id);
                    }
                  }
                }
                $('#user-groups-selectize-form').remove();
                return _this.appendGroupForm(data.groups);
              }
            }).fail((function(error) {
              return console.log(error);
            }));
          };
        })(this));
        group_delete_button.click((function(_this) {
          return function(e) {
            var group_id, name;
            e.preventDefault();
            name = $('#create_group_name_input').val();
            group_id = _this.user_custom_groups[name];
            return jQuery.ajax({
              type: "GET",
              url: '/superphy/collections/delete',
              data: {
                'group_id': group_id
              }
            }).done(function(data) {
              var g, g_obj, ref, ref1;
              if (data.success === 1) {
                ref = usrGrp.viewController.genomeController.public_genomes;
                for (g in ref) {
                  g_obj = ref[g];
                  if (g_obj.isSelected) {
                    g_obj.groups.push(data.group_id);
                  }
                }
                ref1 = usrGrp.viewController.genomeController.private_genomes;
                for (g in ref1) {
                  g_obj = ref1[g];
                  if (g_obj.isSelected) {
                    g_obj.groups.push(data.group_id);
                  }
                }
                $('#user-groups-selectize-form').remove();
                _this.appendGroupForm(data.groups);
              }
              $('#user-groups-selectize-form').remove();
              _this.appendGroupForm(data.groups);
              return console.log(data);
            }).fail((function(error) {
              return console.log(error);
            }));
          };
        })(this));
      }
      custom_select.appendTo(group_select);
      this._processGroups(uGpObj);
      return true;
    };

    UserGroups.prototype._processGroups = function(uGpObj) {
      var $selectized_custom_group_select, custom_groups_select_optgroups, custom_groups_select_options, group, group_collection, group_collection_index, i, j, len, len1, ref, ref1, ref2;
      if (this.username === "") {
        return;
      }
      custom_groups_select_optgroups = [];
      custom_groups_select_options = [];
      ref = uGpObj.custom;
      for (group_collection in ref) {
        group_collection_index = ref[group_collection];
        custom_groups_select_optgroups.push({
          value: group_collection_index.name,
          label: group_collection_index.name,
          count: group_collection_index.children.length
        });
        ref1 = group_collection_index.children;
        for (i = 0, len = ref1.length; i < len; i++) {
          group = ref1[i];
          custom_groups_select_options.push({
            "class": group_collection_index.name,
            value: group.id,
            name: group.name
          });
        }
        ref2 = group_collection_index.children;
        for (j = 0, len1 = ref2.length; j < len1; j++) {
          group = ref2[j];
          this.user_custom_groups[group.name] = group.id;
        }
      }
      $selectized_custom_group_select = $('#custom_group_collections').selectize({
        delimiter: ',',
        persist: false,
        options: custom_groups_select_options,
        optgroups: custom_groups_select_optgroups,
        optgroupField: 'class',
        labelField: 'name',
        searchField: ['name'],
        render: {
          optgroup_header: (function(_this) {
            return function(data, escape) {
              return "<div class='optgroup-header'>" + data.label + " - <span>" + data.count + "</span></div> ";
            };
          })(this),
          option: (function(_this) {
            return function(data, escape) {
              return "<div data-collection_name='" + data["class"] + "' data-group_name='" + data.name + "'>" + data.name + "</div>";
            };
          })(this),
          item: (function(_this) {
            return function(data, escape) {
              return "<div>" + data.name + "</div>";
            };
          })(this)
        },
        create: true
      });
      this.customSelectizeControl = $selectized_custom_group_select[0].selectize;
      return this.customSelectizeControl.on('change', function() {
        return $('#group-query-input').data('group', this.getValue()).data('genome_list', 'private');
      });
    };

    UserGroups.prototype.bonsaiUserGroupList = function(uGpObj) {
      var group, groupHash, group_collection, group_collection_index, i, j, k, l, len, len1, len2, len3, len4, len5, len6, level0Key, level1, level1key, level2, level2key, level3, level3key, m, n, o, ref, ref1, ref2, ref3, ref4, ref5, ref6, ref7, table;
      groupHash = {};
      ref = uGpObj.standard;
      for (group_collection in ref) {
        group_collection_index = ref[group_collection];
        groupHash[group_collection_index.name] = {};
        ref1 = group_collection_index.children;
        for (i = 0, len = ref1.length; i < len; i++) {
          group = ref1[i];
          groupHash[group_collection_index.name][group.name] = {};
          if (group.type === "collection") {
            groupHash[group_collection_index.name][group.name]['type'] = 'collection';
            ref2 = group.children;
            for (j = 0, len1 = ref2.length; j < len1; j++) {
              level1 = ref2[j];
              groupHash[group_collection_index.name][group.name][level1.name] = {};
              if (level1.type === "collection") {
                groupHash[group_collection_index.name][group.name][level1.name]['type'] = 'collection';
                ref3 = level1.children;
                for (k = 0, len2 = ref3.length; k < len2; k++) {
                  level2 = ref3[k];
                  groupHash[group_collection_index.name][group.name][level1.name][level2.name] = {};
                  if (level2.type === "group") {
                    groupHash[group_collection_index.name][group.name][level1.name][level2.name] = {};
                    groupHash[group_collection_index.name][group.name][level1.name][level2.name]['id'] = level2.id;
                    groupHash[group_collection_index.name][group.name][level1.name][level2.name]['type'] = level2.type;
                  }
                }
              }
              if (level1.type === "group") {
                groupHash[group_collection_index.name][group.name][level1.name]['id'] = level1.id;
                groupHash[group_collection_index.name][group.name][level1.name]['type'] = level1.type;
              }
            }
          }
          if (group.type === "group") {
            groupHash[group_collection_index.name][group.name] = {};
            groupHash[group_collection_index.name][group.name]['id'] = group.id;
            groupHash[group_collection_index.name][group.name]['type'] = group.type;
          }
        }
      }
      console.log(groupHash);
      table = "<ol class='group-list' genome_list='public'>";
      ref4 = Object.keys(groupHash).sort();
      for (l = 0, len3 = ref4.length; l < len3; l++) {
        level0Key = ref4[l];
        table += "<li id=" + level0Key + " data-value='false'><label style='font-weight:normal;margin-top:2px;margin-left:5px;'>" + level0Key + "</label>";
        table += "<ol>";
        ref5 = Object.keys(groupHash[level0Key]).sort();
        for (m = 0, len4 = ref5.length; m < len4; m++) {
          level1key = ref5[m];
          level1 = groupHash[level0Key][level1key];
          if (level1['type'] === 'collection') {
            table += "<li id=" + level1key + " data-value='false'><label style='font-weight:normal;margin-top:2px;margin-left:5px;'>" + level1key + "</label>";
            table += "<ol>";
            ref6 = Object.keys(groupHash[level0Key][level1key]).sort();
            for (n = 0, len5 = ref6.length; n < len5; n++) {
              level2key = ref6[n];
              level2 = groupHash[level0Key][level1key][level2key];
              if (level2['type'] === "collection") {
                table += "<li id=" + level2key + " data-value='false'><label style='font-weight:normal;margin-top:2px;margin-left:5px;'>" + level2key + "</label>";
                table += "<ol>";
                ref7 = Object.keys(groupHash[level0Key][level1key][level2key]).sort();
                for (o = 0, len6 = ref7.length; o < len6; o++) {
                  level3key = ref7[o];
                  level3 = groupHash[level0Key][level1key][level2key][level3key];
                  if (level3['type'] === "group") {
                    table += "<li id=\"bonsai" + level2['id'] + "\"  data-value=" + level3['id'] + " data-collection_name=" + level2key + " data-group_name=" + level3key + "><label style='font-weight:normal;line-height:100%;'>" + level3key + "</label></li>";
                  }
                }
                table += "</ol></li>";
              }
              if (level2['type'] === "group") {
                table += "<li id=\"bonsai" + level2['id'] + "\"  data-value=" + level2['id'] + " data-collection_name=" + level1key + " data-group_name=" + level2key + "><label style='font-weight:normal;line-height:100%;'>" + level2key + "</label></li>";
              }
            }
            table += "</ol></li>";
          }
          if (level1['type'] === "group") {
            table += "<li id=\"bonsai" + level1['id'] + "\"  data-value=" + level1['id'] + " data-collection_name=" + level0Key + " data-group_name=" + level1key + "><label style='font-weight:normal;line-height:100%;'>" + level1key + "</label></li>";
          }
        }
        table += "</ol></li>";
      }
      table = table + "</ol>";
      return table;
    };

    UserGroups.prototype._getGroupGenomes = function(group_id, public_genomes, private_genomes) {
      var collection_name, genome_id, genome_obj, group_name, option, select_private_ids, select_public_ids;
      option = $("li[id=bonsai" + group_id + "]", ".group-list");
      collection_name = $(option).data("collection_name");
      group_name = $(option).data("group_name");
      if (typeof select_public_ids === 'undefined') {
        select_public_ids = (function() {
          var ref, results;
          results = [];
          for (genome_id in public_genomes) {
            genome_obj = public_genomes[genome_id];
            if (ref = parseInt(group_id), indexOf.call(genome_obj.groups, ref) >= 0) {
              results.push(genome_id);
            }
          }
          return results;
        })();
      } else if (select_public_ids.indexOf(genome_id) > -1) {
        select_public_ids = (function() {
          var ref, results;
          results = [];
          for (genome_id in public_genomes) {
            genome_obj = public_genomes[genome_id];
            if (ref = parseInt(group_id), indexOf.call(genome_obj.groups, ref) >= 0) {
              results.push(genome_id);
            }
          }
          return results;
        })();
      }
      if (typeof select_private_ids === 'undefined') {
        select_private_ids = (function() {
          var ref, results;
          results = [];
          for (genome_id in private_genomes) {
            genome_obj = private_genomes[genome_id];
            if (ref = parseInt(group_id), indexOf.call(genome_obj.groups, ref) >= 0) {
              results.push(genome_id);
            }
          }
          return results;
        })();
      } else if (select_private_ids.indexOf(genome_id) > -1) {
        select_private_ids = (function() {
          var ref, results;
          results = [];
          for (genome_id in private_genomes) {
            genome_obj = private_genomes[genome_id];
            if (ref = parseInt(group_id), indexOf.call(genome_obj.groups, ref) >= 0) {
              results.push(genome_id);
            }
          }
          return results;
        })();
      }
      return {
        'select_public_ids': select_public_ids,
        'select_private_ids': select_private_ids
      };
    };

    UserGroups.prototype._removeCategoryRadio = function() {
      return $('.group-list').find("input").each(function() {
        if (this.value === 'false') {
          return this.remove();
        } else {
          $("#" + this.id).css({
            'position': 'absolute',
            'height': '100%',
            'margin-top': '0px'
          });
          return $("label[for=" + this.id + "]", '.group-list').css({
            'width': '80%',
            'margin-bottom': '0px',
            'margin-left': '12%'
          });
        }
      });
    };

    UserGroups.prototype._updateSelections = function(select_ids, group_id, genome_list) {
      var bonsai, collection_name, genome_id, group_name, i, j, k, l, len, len1, len2, len3, notification_alert, notification_box, option, private_selected, public_selected, ref, ref1, ref2, ref3;
      this.groupSelected = true;
      this.runSelect = false;
      public_selected = [];
      private_selected = [];
      notification_box = $('#geophy-control-panel-body');
      notification_box.empty();
      ref = Object.keys(viewController.genomeController.public_genomes);
      for (i = 0, len = ref.length; i < len; i++) {
        genome_id = ref[i];
        this.viewController.select(genome_id, false);
      }
      ref1 = Object.keys(viewController.genomeController.private_genomes);
      for (j = 0, len1 = ref1.length; j < len1; j++) {
        genome_id = ref1[j];
        this.viewController.select(genome_id, false);
      }
      if (!select_ids.select_public_ids.length && !select_ids.select_private_ids.length) {
        this.active_group.group_id = '';
        this.active_group.public_list = [];
        this.active_group.private_list = [];
        this.active_group.group_name = '';
        this.groupSelected = false;
        if (this.viewController.views[3] != null) {
          this.viewController.views[3].updateActiveGroup(this);
        }
        this.viewController.views[2].updateActiveGroup(this);
        this.viewController.views[1].updateActiveGroup(this);
        this.viewController.views[0].updateActiveGroup(this);
        bonsai = $('.group-list').data('bonsai');
        bonsai.restore(initialBonsaiState);
        return;
      } else {
        ref2 = select_ids.select_public_ids;
        for (k = 0, len2 = ref2.length; k < len2; k++) {
          genome_id = ref2[k];
          public_selected.push(genome_id);
          if (indexOf.call(viewController.genomeController.pubVisible, genome_id) >= 0) {
            this.viewController.select(genome_id, true);
          }
        }
        ref3 = select_ids.select_private_ids;
        for (l = 0, len3 = ref3.length; l < len3; l++) {
          genome_id = ref3[l];
          private_selected.push(genome_id);
          if (indexOf.call(viewController.genomeController.pvtVisible, genome_id) >= 0) {
            this.viewController.select(genome_id, true);
          }
        }
      }
      this.runSelect = true;
      if (genome_list === "private") {
        option = this.customSelectizeControl.getOption(group_id)[0];
      }
      if ($("li[id=bonsai" + group_id + "]", '.group-list')) {
        option = $("li[id=bonsai" + group_id + "]", '.group-list');
      }
      collection_name = $(option).data("collection_name");
      group_name = $(option).data("group_name");
      this.active_group.group_id = group_id;
      this.active_group.public_list = public_selected;
      this.active_group.private_list = private_selected;
      this.active_group.group_name = group_name;
      notification_alert = $("<div class='alert alert-info' role='alert'>Current group loaded: " + group_name + "</div><br>");
      $("<span clasfgroups='help-block'>" + public_selected.length + " genomes from " + collection_name + " collection</span>").appendTo(notification_alert);
      notification_alert.appendTo(notification_box);
      if (this.viewController.views[3] != null) {
        this.viewController.views[3].updateActiveGroup(this);
      }
      this.viewController.views[2].updateActiveGroup(this);
      this.viewController.views[1].updateActiveGroup(this);
      this.viewController.views[0].updateActiveGroup(this);
      return true;
      return true;
    };

    return UserGroups;

  })();

  if (!root.UserGroups) {
    root.UserGroups = UserGroups;
  }

}).call(this);
