// Generated by CoffeeScript 1.4.0
(function() {
  var onmessage,
    _this = this;

  onmessage = function(uGpObj) {
    var group, groupHash, group_collection, group_collection_index, level0Key, level1, level1key, level2, level2key, level3, level3key, table, _i, _j, _k, _l, _len, _len1, _len2, _len3, _len4, _len5, _len6, _m, _n, _o, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6, _ref7;
    uGpObj = JSON.parse(uGpObj.data);
    groupHash = {};
    _ref = uGpObj.standard;
    for (group_collection in _ref) {
      group_collection_index = _ref[group_collection];
      groupHash[group_collection_index.name] = {};
      _ref1 = group_collection_index.children;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        group = _ref1[_i];
        groupHash[group_collection_index.name][group.name] = {};
        if (group.type === "collection") {
          groupHash[group_collection_index.name][group.name]['type'] = 'collection';
          _ref2 = group.children;
          for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
            level1 = _ref2[_j];
            groupHash[group_collection_index.name][group.name][level1.name] = {};
            if (level1.type === "collection") {
              groupHash[group_collection_index.name][group.name][level1.name]['type'] = 'collection';
              _ref3 = level1.children;
              for (_k = 0, _len2 = _ref3.length; _k < _len2; _k++) {
                level2 = _ref3[_k];
                groupHash[group_collection_index.name][group.name][level1.name][level2.name] = {};
                if (level2.type === "group") {
                  groupHash[group_collection_index.name][group.name][level1.name][level2.name] = {};
                  groupHash[group_collection_index.name][group.name][level1.name][level2.name]['id'] = level2.id;
                  groupHash[group_collection_index.name][group.name][level1.name][level2.name]['type'] = level2.type;
                }
              }
            }
            if (level1.type === "group") {
              groupHash[group_collection_index.name][group.name][level1.name]['id'] = level1.id;
              groupHash[group_collection_index.name][group.name][level1.name]['type'] = level1.type;
            }
          }
        }
        if (group.type === "group") {
          groupHash[group_collection_index.name][group.name] = {};
          groupHash[group_collection_index.name][group.name]['id'] = group.id;
          groupHash[group_collection_index.name][group.name]['type'] = group.type;
        }
      }
    }
    table = "<ol class='group-list' genome_list='public'>";
    _ref4 = Object.keys(groupHash).sort();
    for (_l = 0, _len3 = _ref4.length; _l < _len3; _l++) {
      level0Key = _ref4[_l];
      table += "<li id=" + level0Key + " data-value='false'><label style='font-weight:normal;margin-top:2px;margin-left:5px;'>" + level0Key + "</label>";
      table += "<ol>";
      _ref5 = Object.keys(groupHash[level0Key]).sort();
      for (_m = 0, _len4 = _ref5.length; _m < _len4; _m++) {
        level1key = _ref5[_m];
        level1 = groupHash[level0Key][level1key];
        if (level1['type'] === 'collection') {
          table += "<li id=" + level1key + " data-value='false'><label style='font-weight:normal;margin-top:2px;margin-left:5px;'>" + level1key + "</label>";
          table += "<ol>";
          _ref6 = Object.keys(groupHash[level0Key][level1key]).sort();
          for (_n = 0, _len5 = _ref6.length; _n < _len5; _n++) {
            level2key = _ref6[_n];
            level2 = groupHash[level0Key][level1key][level2key];
            if (level2['type'] === "collection") {
              table += "<li id=" + level2key + " data-value='false'><label style='font-weight:normal;margin-top:2px;margin-left:5px;'>" + level2key + "</label>";
              table += "<ol>";
              _ref7 = Object.keys(groupHash[level0Key][level1key][level2key]).sort();
              for (_o = 0, _len6 = _ref7.length; _o < _len6; _o++) {
                level3key = _ref7[_o];
                level3 = groupHash[level0Key][level1key][level2key][level3key];
                if (level3['type'] === "group") {
                  table += "<li id=\"bonsai" + level2['id'] + "\"  data-value=" + level3['id'] + " data-collection_name=" + level2key + " data-group_name=" + level3key + "><label style='font-weight:normal;line-height:100%;'>" + level3key + "</label></li>";
                }
              }
              table += "</ol></li>";
            }
            if (level2['type'] === "group") {
              table += "<li id=\"bonsai" + level2['id'] + "\"  data-value=" + level2['id'] + " data-collection_name=" + level1key + " data-group_name=" + level2key + "><label style='font-weight:normal;line-height:100%;'>" + level2key + "</label></li>";
            }
          }
          table += "</ol></li>";
        }
        if (level1['type'] === "group") {
          table += "<li id=\"bonsai" + level1['id'] + "\"  data-value=" + level1['id'] + " data-collection_name=" + level0Key + " data-group_name=" + level1key + "><label style='font-weight:normal;line-height:100%;'>" + level1key + "</label></li>";
        }
      }
      table += "</ol></li>";
    }
    table = table + "</ol>";
    postMessage(table);
    return 0;
  };

}).call(this);
