// Generated by CoffeeScript 1.4.0
(function() {
  var onmessage,
    _this = this;

  onmessage = function(map) {
    var circleIcon, clusteredMarkers, marker, markerList, marker_id, masterObject, newMarkers;
    console.log(map);
    masterObject = JSON.parse(map);
    markerList = masterObject['list'];
    circleIcon = masterObject['circle'];
    map = masterObject['map'];
    clusteredMarkers = [];
    for (marker_id in markerList) {
      marker = markerList[marker_id];
      marker.setMap(map);
      marker.setIcon(circleIcon);
      _this.clusteredMarkers.push(marker);
    }
    newMarkers = JSON.stringify(_this.clusteredMarkers);
    return postMessage(newMarkers);
  };

}).call(this);
